### ISSUE TITLE
pip-compile raises an exception when setup.py has a URL in install_requires directive

### ISSUE THREAD

**Issue by atugushev** [jazzband/pip-tools#1346]
#### Environment Versions

1. OS Type: macOS
1. Python version: `3.8.0`
1. pip version: `21.0.1`
1. pip-tools version: 9aeeed133504cfbeafb5e640290cd3c85ed3c651

#### Steps to replicate

1. Create `setup.py`
```python
# setup.py
from setuptools import setup

setup(
    name="foo",
    version="0.1",
    install_requires=["six @ git+https://github.com/benjaminp/six#egg=six"],
)
```
2. Run `pip-compile`

#### Expected result

Works with `pip-tools==5.5.0`:

```ini
$ pip-compile
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile
#
git+https://github.com/benjaminp/six#egg=six
    # via foo (setup.py)
```

#### Actual result

```python
$ pip-compile
Traceback (most recent call last):
  File "/Users/albert/Projects/pip-tools/.venv/bin/pip-compile", line 33, in <module>
    sys.exit(load_entry_point('pip-tools', 'console_scripts', 'pip-compile')())
  File "/Users/albert/Projects/pip-tools/.venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/albert/Projects/pip-tools/.venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/albert/Projects/pip-tools/.venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/albert/Projects/pip-tools/.venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/albert/Projects/pip-tools/.venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/albert/Projects/pip-tools/piptools/scripts/compile.py", line 361, in cli
    [
  File "/Users/albert/Projects/pip-tools/piptools/scripts/compile.py", line 362, in <listcomp>
    install_req_from_req_string(req, comes_from=comes_from)
  File "/Users/albert/Projects/pip-tools/.venv/lib/python3.8/site-packages/pip/_internal/req/constructors.py", line 422, in install_req_from_req_string
    if (req.url and comes_from and comes_from.link and
AttributeError: 'str' object has no attribute 'link'
```

#### Additional context
- introduced in #1311
- [install_req_from_req_string(comes_from=...)](https://github.com/pypa/pip/blob/31eb524ff0d18d6190b30a0c7821c0c857a7523c/src/pip/_internal/req/constructors.py#L415) accepts only optional `InsallRequirement`
- [install_req_from_line](https://github.com/pypa/pip/blob/31eb524ff0d18d6190b30a0c7821c0c857a7523c/src/pip/_internal/req/constructors.py#L382) can be used instead of `install_req_from_req_string`

/cc @astrojuanlu
