### ISSUE TITLE
Fails with 3.13.4

### ISSUE THREAD

**Issue by daveisfera** [jazzband/pip-tools#2193]
`pip-compile` works with 3.13.3 but breaks with 3.13.4 and later

#### Environment Versions

1. Debian Bookworm
1. Python version: `Python 3.13.4 (main, Jun 10 2025, 23:56:29) [GCC 12.2.0] on linux`
1. pip version: `pip 25.1.1 from /usr/local/lib/python3.13/site-packages/pip (python 3.13)`
1. pip-tools version: `pip-compile, version 7.4.1`

#### Steps to replicate

1. Verify working on Python 3.13.3
2. Upgrade to Python 3.13.4
3. Observe error

#### Expected result

Works with latest point release of Python 3.13

#### Actual result

```
Traceback (most recent call last):
  File "/usr/local/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
             ~~~^^
  File "/usr/local/lib/python3.13/site-packages/click/core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/click/core.py", line 1363, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.13/site-packages/click/core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/click/core.py", line 794, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/piptools/scripts/compile.py", line 471, in cli
    hashes = resolver.resolve_hashes(results) if generate_hashes else None
             ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/piptools/resolver.py", line 167, in resolve_hashes
    with self.repository.allow_all_wheels(), log.indentation():
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/contextlib.py", line 141, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.13/site-packages/piptools/repositories/pypi.py", line 452, in allow_all_wheels
    self.finder.find_all_candidates.cache_clear()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'cache_clear'
```

**Comment by sirosen** [comment]
I think the issue you're seeing is that `pip-tools` currently doesn't work with `pip>=25.0`.
You should try installing `pip==24.2` or a similar version to see if that works for you as a workaround for now.

---

We have a number of issues to fix to get `pip-tools` healthy again, and this is one of them. There are open PRs and work in progress, and we're trying to get things into a good state for a new release soon.

**Comment by daveisfera** [comment]
So the issue is `25.1` vs `25.0`? Because 3.13.3 is using `25.0.1`:
```
pip 25.0.1 from /usr/local/lib/python3.13/site-packages/pip (python 3.13)
```

**Comment by sirosen** [comment]
No, the issue is present with 25.0 and all higher versions. We only just got back to healthy CI against Python 3.12 -- we aren't even testing `pip-tools` on 3.13 yet.
I know that in practice I'm using `pip-tools` on 3.13 with a lower version of pip and it's working for me, so it will probably work for you.

There's been a lot of drift without proper maintenance here and we're trying to fix it, but it's going to take time.

**Comment by AndydeCleyre** [comment]
FWIW I've been getting along as long as pip is <25.1
