### ISSUE TITLE
pip-sync Installs from sdist (.zip) after pip-compile --generate-hashes

### ISSUE THREAD

**Issue by ssiano** [jazzband/pip-tools#1485]
<!-- Describe the issue briefly here. -->

#### Environment Versions

1. Ubuntu 14.04
1. Python version: 3.6.8
1. pip version: 21.2.4
1. pip-tools version: 6.2.0

#### Steps to replicate
The following was done in a virtualenv named pip-tools:
```
ss@ld:~/venv/PY3/pip-tools$ pip list
Package            Version
------------------ --------
click              8.0.1
importlib-metadata 4.8.1
pep517             0.11.0
pip                21.2.4
pip-tools          6.2.0
setuptools         58.0.4
tomli              1.2.1
typing-extensions  3.10.0.2
wheel              0.37.0
zipp               3.5.0
(pip-tools) 

ss@ld:~/venv/PY3/pip-tools$ cat requirements.in 
pygraphviz==1.5
(pip-tools) 

ss@ld:~/venv/PY3/pip-tools$ pip-compile
#
# This file is autogenerated by pip-compile with python 3.6
# To update, run:
#
#    pip-compile
#
--index-url https://pypi.COMPANY.com/simple/

pygraphviz==1.5
    # via -r requirements.in
(pip-tools) 

ss@ld:~/venv/PY3/pip-tools$ pip-sync --pip-args "--no-cache-dir"                                                                                                                                                                                                                                                                                                          
Looking in indexes: https://pypi.COMPANY.com/simple/
Collecting pygraphviz==1.5
  Downloading https://pypi.COMPANY.com/pygraphviz/1.5/pygraphviz-1.5-cp36-cp36m-linux_x86_64.whl (150 kB)
     |████████████████████████████████| 150 kB 19.9 MB/s 
Installing collected packages: pygraphviz
Successfully installed pygraphviz-1.5
(pip-tools) 

ss@ld:~/venv/PY3/pip-tools$ pip uninstall -y pygraphviz                                                                                                                                                                                                                                                                                                                   
Found existing installation: pygraphviz 1.5
Uninstalling pygraphviz-1.5:
  Successfully uninstalled pygraphviz-1.5
(pip-tools) 

ss@ld:~/venv/PY3/pip-tools$ pip-compile --generate-hashes
    Couldn't get hashes from PyPI, fallback to hashing files
#
# This file is autogenerated by pip-compile with python 3.6
# To update, run:
#
#    pip-compile --generate-hashes
#
--index-url https://pypi.COMPANY.com/simple/

pygraphviz==1.5 \
    --hash=sha256:50a829a305dc5a0fd1f9590748b19fece756093b581ac91e00c2c27c651d319d \
    --hash=sha256:99007fe4432d38c8d3ae40c9ceddccad88eaef88b319a8787fdb1aeceeeb1671
    # via -r requirements.in
(pip-tools) 

ss@ld:~/venv/PY3/pip-tools$ pip-sync --pip-args "--no-cache-dir"                                                                                                                                                                                                                                                                                                          
Looking in indexes: https://pypi.COMPANY.com/simple/
Collecting pygraphviz==1.5
  Downloading https://pypi.COMPANY.com/packages/packages/7e/b1/d6d849ddaf6f11036f9980d433f383d4c13d1ebcfc3cd09bc845bda7e433/pygraphviz-1.5.zip (117 kB)
     |████████████████████████████████| 117 kB 22.7 MB/s 
Building wheels for collected packages: pygraphviz
  Building wheel for pygraphviz (setup.py) ... error
  ERROR: Command errored out with exit status 1:
...
pygraphviz/graphviz_wrap.c:2987:29: fatal error: graphviz/cgraph.h: No such file or directory
...
subprocess.CalledProcessError: Command '['/home/ssiano/venv/PY3/pip-tools/bin/python3.6', '-m', 'pip', 'install', '-r', '/tmp/tmp0tcqn2sm', '--index-url', 'https://pypi.zooxlabs.com/simple/', '--no-cache-dir']' returned non-zero exit status 1.
```

#### Expected result
Expected pip-sync to use the wheel whether or not the requirements.txt contained hashes.

#### Actual result
pip-sync used the wheel when requirements.txt did not contain hashes, and attempted to build the sdist (.zip) when requirements.txt did contain hashes.

I should mention that unlike pypi.org, both the .whl and the .zip exist in our Artifactory/PyPI:
```
ss@ld:~/venv/PY3/pip-tools$ jfrog rt search 'pypi/*/pygraphviz-1.5*'
[Info] Searching artifacts...
[Info] Found 2 artifacts.
[
  {
    "path": "files.pythonhosted.org-cache/7e/b1/d6d849ddaf6f11036f9980d433f383d4c13d1ebcfc3cd09bc845bda7e433/pygraphviz-1.5.zip",
    "type": "file",
    "size": 117810,
    "created": "2020-02-12T07:47:40.529Z",
    "modified": "2018-09-10T22:19:11.000Z",
    "sha1": "0171c160cc9cbec28162204b514f8595e2c88dac",
    "md5": "c186f5f6567e523a862063fc62ddcd2f",
    "props": {
      "artifactory.internal.etag": [
        "\"c186f5f6567e523a862063fc62ddcd2f\""
      ]
    }
  },
  {
    "path": "pypi-COMPANY/pygraphviz/1.5/pygraphviz-1.5-cp36-cp36m-linux_x86_64.whl",
    "type": "file",
    "size": 150257,
    "created": "2021-06-11T04:36:06.918Z",
    "modified": "2021-06-11T04:36:06.851Z",
    "sha1": "13a5974b031705bcc98c7b6a0985318784541f36",
    "md5": "ae9fe3872eb6e09bbf42a9bb51275c4c",
    "props": {
      "pypi.name": [
        "pygraphviz"
      ],
      "pypi.normalized.name": [
        "pygraphviz"
      ],
      "pypi.requires.python": [
        ""
      ],
      "pypi.summary": [
        "Python interface to Graphviz"
      ],
      "pypi.version": [
        "1.5"
      ]
    }
  }
]
(pip-tools)
```

I should also mention that our PyPI/Artifactory is an older version that does not return sha256 values, as can be seen in the JSON output above.

**Comment by ssiano** [comment]
If I pip-compile with --generate-hashes and then remove the sha256 for the .zip from requirements.txt, then pip-sync uses the wheel.

**Comment by ssiano** [comment]
This issue has been solved by upgrading our PyPI/Artifactory to a version that contains the following fix:
[SHA256 hashes in PyPi repository metadata](https://www.jfrog.com/jira/browse/RTFACT-18495).

Now pip-sync installs the wheel when both hashes are in the requirements.txt.

Before, pip-sync was choosing the artifact with the lowest hash value.  It probably would have been better for pip-sync to fail with an error message.

But this is a strange corner case, so I think this issue should be closed.
