### ISSUE TITLE
pip-compile fails if output file already exists

### ISSUE THREAD

**Issue by jredwards** [jazzband/pip-tools#484]
Given a requirements.in file which consists only of the line:
```
-e ..
```
(that is, pull in requirements from the setup.py file one folder up from my requirements.in file)

The first pip-compile run works fine. The second one throws an error. If I delete the file that was generated by the first run, it will work again. There are no permissions issues (tried it with full perms on the file to check).

##### Environment Versions

1. os: OSX 10.11.6
1. python version: 2.7
1. pip version: 9.0.1
1. pip-tools version: 1.8.2

##### Steps to replicate

1. pip-compile -v -o requirements.txt
**SUCCESS**
2. pip-compile -v -o requirements.txt 
**FAILURE**

##### Expected result
An updated (or identical) requirements.txt file

##### Actual result
```python
Traceback (most recent call last):
  File "/Users/<username>/.virtualenvs/<virtualenv>/bin/pip-compile", line 11, in <module>
    sys.exit(cli())
  File "/Users/<username>/.virtualenvs/<virtualenv>/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/<username>/.virtualenvs/<virtualenv>/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/<username>/.virtualenvs/<virtualenv>/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/<username>/.virtualenvs/<virtualenv>/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/<username>/.virtualenvs/<virtualenv>/lib/python2.7/site-packages/piptools/scripts/compile.py", line 131, in cli
    key = key_from_req(ireq.req)
  File "/Users/<username>/.virtualenvs/<virtualenv>/lib/python2.7/site-packages/piptools/utils.py", line 41, in key_from_req
    key = req.name
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by davidovich** [comment]
This issue should be fixed in the (unreleased) 1.9.0. Can you check that your use case is covered on the master branch? Thanks.

see #477

**Comment by jredwards** [comment]
My use case appears to be broken entirely in the master branch (i.e. it does not work even if the output file does not exist). 

I ran the same command on the same .in file. 

Here is the version, according to pip-compile --version:
```
pip-compile, version 1.8.3.dev23-ng62d85ea
```

Here is my output:
```python
⇒  pip-compile -v requirements.in -o requirements.txt
Using indexes:
  https://pypi.python.org/simple
Traceback (most recent call last):
  File "/Users/<username>/.virtualenvs/<virtualenv>/bin/pip-compile", line 9, in <module>
    load_entry_point('pip-tools==1.8.3.dev23-ng62d85ea', 'console_scripts', 'pip-compile')()
  File "/Users/<username>/.virtualenvs/<virtualenv>/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/<username>/.virtualenvs/<virtualenv>/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/<username>/.virtualenvs/<virtualenv>/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/<username>/.virtualenvs/<virtualenv>/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/<username>/workspace/Local/cloned/pip-tools/piptools/scripts/compile.py", line 183, in cli
    primary_packages = {key_from_req(ireq.req) for ireq in constraints if not ireq.constraint}
  File "/Users/<username>/workspace/Local/cloned/pip-tools/piptools/scripts/compile.py", line 183, in <setcomp>
    primary_packages = {key_from_req(ireq.req) for ireq in constraints if not ireq.constraint}
  File "/Users/<username>/workspace/Local/cloned/pip-tools/piptools/utils.py", line 44, in key_from_req
    key = req.name
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by jredwards** [comment]
To be fair, I believe my use case was working in 1.7.0, broken in 1.8.0 and 1.8.1, semi-working in 1.8.2 (with the error that I started this issue with), and now broken again in master.

**Comment by davidovich** [comment]
OK, this was introduced by 5bf5b97db36f7ade80cbce40b4de2175886f7100

Will fix and add a test.
